### ISSUE TITLE
关于算法模块的问题

### ISSUE THREAD

**Issue by bytesc** [iqpeppel/simple-crm-system#6]
@kalipolis 算法模块需做如下修改 

#2 

1. 适配sqlite3数据库，详见项目 readme，如果需要数据库相关适配，请联系我
2. 文件名不要非 ascii 字符
3. 数据库连接应该与核心算法分离
4. 相关代码应该集中放在一个文件夹，而不是直接放根目录
5. 缺少说明文档（用法和原理的简单说明）

**Comment by kalipolis** [comment]
**坚决听从**@bytesc的指示:open_hands:~~但是我先摸一周~~

**Comment by bytesc** [comment]
1. issue 不讨论与项目本身无关话题。
